name: Cep Finder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/cepfinder .

      - name: Push image docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/cepfinder

  deploy:
    needs: build
    runs-on: self-hosted  # A máquina onde o Docker e Docker Compose estão configurados
    steps:
      - name: Pull image from docker hub
        run: |
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/cepfinder:latest
      - name: Remove docker container
        run: |
          docker rm -f app-cepfinder
      - name: Run docker container
        run: |
          sudo docker run -d -p 8080:8080 \
            -e DATABASE_URL=${{secrets.DATABASE_URL}} \
            -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} \
            -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} \
            --name app-cepfinder ${{secrets.DOCKER_USERNAME}}/cepfinder
